### ISSUE TITLE
Make pyslim conda-installable.

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#10]
I gather that's a better way to do things. I've set up a [PyPI](https://pypi.org/manage/project/pyslim/releases/) account, but not conda-forge.

**Comment by jeromekelleher** [comment]
I can do it if you prefer --- it's pretty trivial to set up a conda recipe for a pure-Python setup like this.

**Comment by jeromekelleher** [comment]
OK, please ping me when there's a version ready for conda-forging and I'll make a recipe.

**Comment by mcneney** [comment]
A conda-installable version would be great. Is there an ETA for this?  Thanks. -b

**Comment by jeromekelleher** [comment]
We need to have pyslim on conda-forge for stdpopsim - any objections if I go ahead with it @petrelharp?

**Comment by petrelharp** [comment]
Please! I've started to look into this a couple of times, but how to do it has remained opaque.

**Comment by jeromekelleher** [comment]
Will do.

**Comment by jeromekelleher** [comment]
Huh, turns out that @winni2k has made a bioconda recipe:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pyslim/meta.yaml

My initial conda-forge PR here: https://github.com/conda-forge/staged-recipes/pull/11764

So, great! We already have a working recipe. It's a little bit awkward that the recipe is on bioconda, given that all of the other tskit and stdpopsim stuff is upstream in conda-forge. @winni2k, would you have any objection to moving your recipe to conda-forge, or would you prefer to keep it on bioconda?

**Comment by winni2k** [comment]
Haha, I did not realize that the other tools were in conda-forge. I just packaged pyslim up when I needed it for some work and put it where I thought it would be most appropriate. I am happy for the pyslim recipe to be moved to conda-forge, and I am happy to take on the task as well.

But can I ask, wouldn't bioconda be a more appropriate place for some of the tskit and stdpopsim packages that are more clearly biological in nature?

**Comment by jeromekelleher** [comment]
> I am happy for the pyslim recipe to be moved to conda-forge, and I am happy to take on the task as well.

Great, thanks @winni2k! I'd imagine there's a process for migrating, so please keep me in the loop (or, I'm happy to get the wheels moving).

> But can I ask, wouldn't bioconda be a more appropriate place for some of the tskit and stdpopsim packages that are more clearly biological in nature?

The original reason for going with conda-forge rather than bioconda was windows support (bioconda didn't do windows a few years ago, not sure if it does now). I think the two projects are increasingly aligning now, and conda-forge is an upstream requirement for bioconda. So, going with conda-forge makes things a bit easier for users, as there's only one channel to manage.

**Comment by winni2k** [comment]
Alright, it looks like the pyslim package has been moved to conda-forge. The already existing packages on bioconda cannot be removed, but any newer versions will only appear on conda-forge.

```
conda install pyslim

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/warkre/miniconda3

  added / updated specs:
    - pyslim


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.4.5.1         |   py37hc8dfbb8_0         151 KB  conda-forge
    gsl-2.6                    |       ha2d443c_0         3.0 MB  conda-forge
    humanize-2.4.0             |             py_0          33 KB  conda-forge
    importlib-metadata-1.6.0   |   py37hc8dfbb8_0          42 KB  conda-forge
    importlib_metadata-1.6.0   |                0           3 KB  conda-forge
    jsonschema-3.2.0           |   py37hc8dfbb8_1          89 KB  conda-forge
    kastore-0.2.2              |   py37h3b54f70_1          33 KB  conda-forge
    llvm-openmp-10.0.0         |       h28b9765_0         268 KB  conda-forge
    msprime-0.7.4              |   py37h4caa599_1         196 KB  conda-forge
    numpy-1.18.4               |   py37h7687784_0         5.1 MB  conda-forge
    pyparsing-2.4.7            |     pyh9f0ad1d_0          60 KB  conda-forge
    pyrsistent-0.16.0          |   py37h9bfed18_0          87 KB  conda-forge
    pyslim-0.401               |     pyh9f0ad1d_0          19 KB  conda-forge
    svgwrite-1.4               |             py_2          50 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         9.1 MB

```

**Comment by winni2k** [comment]
FYI the PR to remove pyslim from bioconda is here: https://github.com/bioconda/bioconda-recipes/pull/22435

**Comment by jeromekelleher** [comment]
Woot! Thanks @winni2k, this is great!

Should we add me/@petrelharp to the maintainers list for the recipe to reduce the bus factor?

**Comment by winni2k** [comment]
Sure thing. Just make a PR adding you two as maintainers.

**Comment by jeromekelleher** [comment]
Done. I think we can close this now - thanks again @winni2k!
