### ISSUE TITLE
recapitate incompatible with updates in msprime

### ISSUE THREAD

**Issue by mufernando** [tskit-dev/pyslim#106]
msprime removed some arguments from simulate recently (e.g., discrete_genomes), so pyslim needs to be updated to use `sim_ancestry`.

**Comment by jeromekelleher** [comment]
Also note the change of parameter name ``from_ts`` to ``initial_state``.

**Comment by petrelharp** [comment]
Ok, here's the summary of what [recapitate did](https://github.com/tskit-dev/pyslim/blob/ced273690ca930ef27f6efa205ea20ff419e7361/pyslim/slim_tree_sequence.py#L441)

1. used a discrete recombination map by default - *no longer necessary*
2. set up population configurations for each population if not provided
3. sets the `start_time` to the `slim_generation`- *not necessary since all the input roots should be present at the right time*

Somehow, it didn't keep the reference sequence, whoops.

The most common use case is probably (a) with a single SLiM population, (b) simulate an ancestral population of fixed size. However, since the SLiM population will probably be `p1`, there will be another, empty, population. To do this, I think we need to do:
```
d = msprime.Demography([msprime.Population(initial_size=1000) for _ in slim_ts.populations()])
msprime.sim_ancestry(initial_state=slim_ts, demography=d)
```
The only odd thing about this is that the user has to define *two* populations, despite only using one. So, recapitate could take care of this situation by default, and I'm not sure what else useful it could do.  (Alternatively, I guess we could recommend doing `simplify(keep_input_roots=True)` first to get rid of spurious populations, but that seems equally confusing and more perilous.)

Right now I'm leaning towards getting rid of `recapitate` entirely. (We can still call the procedure "recapitation" in the manual, though.)

**Comment by grahamgower** [comment]
I don't have any concrete suggestions here, but just wanted to say that populations need human-readable names, rather than numerical IDs. The IDs are a pain, and it's so easy to make mistakes. So, it would be ideal if there were names on the SLiM side that would then be matched up on the msprime side. I haven't followed all the tskit metadata improvements in the past 12 months, but I guess this is now possible?

**Comment by jeromekelleher** [comment]
You could provide a function ``make_demography(ts_produced_by_slim)`` or something, which could inspect the SLiM metadata and construct the appropriate msprime Demography (or, indeed, Demes graph) for simulating with? Ideally you'd want to set the population sizes automatically from the final state of the SLiM sim, right?

If we then used population names  rather than IDs as @grahamgower suggests, this could all be quite smooth and straightforward.

**Comment by petrelharp** [comment]
How do the population names work? Does msprime just look for a `pop.metadata['name']` property?

**Comment by petrelharp** [comment]
I love the `make_demography( )` idea, but I don't think we have enough information to do it: we don't know how big the populations should be! And, if we did, it'd be the values at the *end* of the simulation, not at the start. We *could* change things somehow to store the initial population size for each population as well (for WF models only, probably), but then you also have to start worrying that "population 1" at the end of the simulation may not be the same as "population 1" at the start. We don't have a very strong expectation that the ancestral demography should be the same as today's; and it seems easy enough for the user to input the necessary demography.

And: I still haven't figured out how the names will make things smoother. Is it about specifying samples? The default names in SLiM will be `p0`, `p1`, etcetera, and there isn't much difference between `{ 1: 10 }` and `{ "p1" : 10 }`.

**Comment by grahamgower** [comment]
> And: I still haven't figured out how the names will make things smoother. Is it about specifying samples? The default names in SLiM will be `p0`, `p1`, etcetera, and there isn't much difference between `{ 1: 10 }` and `{ "p1" : 10 }`.

For the most part, it's about usability of the final tree sequence. If you're constructing a demography object here without population names, then there won't be any for the user afterwards. I suppose the problem here is that there are no names associated with populations in SLIM, so there are no names available in the metadata read by pyslim?

**Comment by petrelharp** [comment]
> For the most part, it's about usability of the final tree sequence. If you're constructing a demography object here without population names, then there won't be any for the user afterwards. I suppose the problem here is that there are no names associated with populations in SLIM, so there are no names available in the metadata read by pyslim?

Right, the SLiM metadata does not have a "name" slot. We should add one, I suppose, although it'll be a bit annoying. Right now, even if the Demography object has names, the output from `sim_ancestry(initial_state=... )` does *not*, because it leaves the SLiM-produced population tables untouched (as it should).

**Comment by petrelharp** [comment]
I've got a version of this [here](https://github.com/tskit-dev/pyslim/blob/625295ba6b4ae8e8400953be65b03b3630c1430f/pyslim/methods.py#L10); I think the approach is good, but would love to get some other input.

**Comment by petrelharp** [comment]
and, FYI, we're planning to put a 'name' and 'description' slot into SLiM population metadata.

**Comment by grahamgower** [comment]
> I've got a version of this [here](https://github.com/tskit-dev/pyslim/blob/625295ba6b4ae8e8400953be65b03b3630c1430f/pyslim/methods.py#L10); I think the approach is good, but would love to get some other input.

Cool! Does the constructed demography end up in the metadata? If so, It might be confusing (e.g. seeing all populations have the ancestral population as a direct ancestor). But otherwise, that looks like a fine way of doing recapitation.

**Comment by petrelharp** [comment]
> Does the constructed demography end up in the metadata?

It does not.

**Comment by petrelharp** [comment]
I'm closing this with the new `pyslim.recapitate( )` in #224; probably it can be made more flexible somehow to include the case of recapitating with more than one population, but how that would work (and be easier than just doing `msprime.sim_ancestry( )`) is unclear to me so far.
