### ISSUE TITLE
Provide method to output to A/C/G/T

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#17]
We should be able to output code to e.g. VCF format, for which we'll need to turn alleles into something friendlier like ACGT.

This can be easy, though: this should be a one-way operation, not something that we want to be able to reverse.

**Comment by petrelharp** [comment]
cc @benhaller

**Comment by bhaller** [comment]
Ah, I didn't see this until now because you tagged "benhaller" but I'm @bhaller (or at least I think I am :->).  Yes, sure, this would be nice; and of course if actual nucleotides are present for mutations, and there's an ancestral sequence, then those things ought to be used in the VCF data generated.  On the other hand, SLiM now does all of this; so maybe there's not really a need for pyslim to do it also?  As long as the .trees file can be read into SLiM, people could use SLiM to generate the VCF output file.  But if you do want to get into it, perhaps the way I've done it in SLiM might be useful to look at; see outputVCF() / outputVCFSample() in the (upcoming) SLiM 3.3 manual.

**Comment by petrelharp** [comment]
SLiM has nucleotide mutations, but this is still something we need to think about in the future. I'm closing this now anyhow because this is not a concrete proposal and it's not at all clear how to do it.
