### ISSUE TITLE
Recapitating with non-uniform recombination rates

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/pyslim#20]
> You cannot use msprime to recapitate a SLiM simulation using a recombination map that is not uniform. This is because msprime and SLiM both use discrete recombination maps, but SLiM is discrete in physical coordinates (base pairs), while msprime is discrete in genetic map units. You can run a simulation in SLiM using any recombination map you want, and then recapitate using a uniform map in msprime (this is the default). See the msprime documentation for more discussion of recapitation.

FYI, this feature would be useful to me!

**Comment by petrelharp** [comment]
So far, we haven't been able to see how to do this without major replumbing under the `msprime` hood.

But, as I write this...

The basic problem is that the recombination breakpoints output by SLiM may not match the possible recombination breakpoints that msprime will use. Because of how msprime works under the hood, they have to. **But**, we could

1. make a maximally-fine-but-still-discrete recombination map in msprime
2. remap the breakpoint positions in the input tree sequence to their nearest smaller position in the msprime map
3. warn/error if this has moved any breakpoints more than some distance or has caused anything else bad to happen
4. proceed with recapitation

Perhaps steps 2 and 3 would be a method that would take a tree sequence and a recombination map.  This should work just fine, moving breakpoints by no more than something very small **unless** there are regions with zero recombination rate. At first I thought it should be in `pyslim` because you're doing something not-quite-right with a tree sequence that is mostly useful for SLiM->msprime; but actually you'd run into the same problem if you tried to do `msprime.simulate(... from_ts=ts)` with a `ts` that was made with a different recombination map.

What do you think, @jeromekelleher? Does this, vaguely, make sense?

**Comment by jeromekelleher** [comment]
I think this makes sense @petrelharp, and can be tried without needing to make any changes internally to msprime. I guess msprime could provide a function ``remap_coordinates(ts, recombination_map)`` which does what you describe, if it works. You can then recapitate with the output of ``remap_coordinates`` (this is better than doing this internally within ``msprime.simulate`` I think, because the interface is already complex enough).

Unfortunately I don't have time to work on this at the moment though.

**Comment by petrelharp** [comment]
Sounds good. I don't have time to do this quite at the moment either, but can populate an issue over at msprime with our notes on this process if someone else wants to start on it.

**Comment by mufernando** [comment]
This has been possible since 1223afd31f769f1eb41ec5b625cb90a9d2ce9565 (?)

**Comment by jeromekelleher** [comment]
This problem should go away entirely after msprime 1.0.

**Comment by petrelharp** [comment]
> This has been possible since 1223afd (?)

True - you can pass in a recombination map - the thing quoted above was saying that it's not always possible to have *exactly* the same recombination map, for reasons related to discretization.

But - not an issue any more. I'll close this and open an issue saying that we should document this or give an example.
