### ISSUE TITLE
Error with pyslim.load 'AttributeError: can't set attribute'

### ISSUE THREAD

**Issue by asadrh8** [tskit-dev/pyslim#266]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/73436736/175128213-2c2fd57e-45b8-47cc-b412-9341b5447272.png">

Hi,
I've been running into an issue with loading in TreeSeq files on CoLab (picture attached). I've instead tried using tskit.load, but following that I'm met with an error using msprime.sim_mutations() (The error is as follows: 'LibraryError: Existing allele(s) incompatible with mutation model alphabet.')
Thanks,
Asad

**Comment by petrelharp** [comment]
Ah-ha - this is an incompatibility between the new tskit release and the previous pyslim. In fact, in the next pyslim release, `pyslim.load( )` is removed, as  the functionality has shifted over to tskit. The beta release of pyslim 1.0: https://pypi.org/project/pyslim/1.0b1/ .

So, I'm guessing that the problem "incompatible with mutation model alphabet" occurs because you're trying to add nucleotide mutations to a tree sequence with SLiM mutations. (By default, `sim_mutations( )` uses Jukes-Cantor, with ACGT alleles.) To get around this, you could either [add mutations using the SLiMMutationModel](https://tskit.dev/pyslim/docs/latest/tutorial.html#adding-neutral-mutations-to-a-slim-simulation), or you could first [convert alleles to nucleotides](https://tskit.dev/pyslim/docs/latest/python_api.html#pyslim.convert_alleles) (but be sure to read the caveats for the latter function).

Let me know if this fixes your problem?

**Comment by petrelharp** [comment]
For completeness, you'd install the beta with
```
pip install pyslim==1.0b1
```
I'll close this, please let us know if you've still got issues.

**Comment by asadrh8** [comment]
> Ah-ha - this is an incompatibility between the new tskit release and the previous pyslim. In fact, in the next pyslim release, `pyslim.load( )` is removed, as the functionality has shifted over to tskit. The beta release of pyslim 1.0: https://pypi.org/project/pyslim/1.0b1/ .
> 
> So, I'm guessing that the problem "incompatible with mutation model alphabet" occurs because you're trying to add nucleotide mutations to a tree sequence with SLiM mutations. (By default, `sim_mutations( )` uses Jukes-Cantor, with ACGT alleles.) To get around this, you could either [add mutations using the SLiMMutationModel](https://tskit.dev/pyslim/docs/latest/tutorial.html#adding-neutral-mutations-to-a-slim-simulation), or you could first [convert alleles to nucleotides](https://tskit.dev/pyslim/docs/latest/python_api.html#pyslim.convert_alleles) (but be sure to read the caveats for the latter function).
> 
> Let me know if this fixes your problem?

It worked! Thank you.
