### ISSUE TITLE
readthedocs not autoclassing

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#52]
In the [python api](https://pyslim.readthedocs.io/en/latest/python_api.html) section, the additional members of the SlimTreeSequence are supposed to be listed, and are when I build locally. But they are not on readthedocs. Looking at [the logs](https://readthedocs.org/projects/pyslim/builds/) there were import errors that I made dissappear by [this magic](https://github.com/tskit-dev/pyslim/commit/9fd88dd07110aae2991e65b88f3f9416a1bc7888#diff-85987f48f1258d9ee486e3191495582dR19), which I thought was odd since tskit does not do this. But now [there are no errors](https://readthedocs.org/api/v2/build/9696436.txt) and yet the members are not there. Anyone have any idea what's going on? @jeromekelleher or @molpopgen maybe?

**Comment by jeromekelleher** [comment]
The magic mock stuff is there so that you don't have to build extension modules on RTD. This is an issue for msprime, because it depends on GSL. I'd remove all the modules you have in the mock list except msprime and see what happens. You need to add a requirements.txt for the ones that will work.

I doubt it'll work unless you have tskit installing on RTD at the least anyway.

**Comment by petrelharp** [comment]
requirements.txt!! Thanks; got it!
