### ISSUE TITLE
Inconsistent mutations: state already equal to derived state

### ISSUE THREAD

**Issue by josieparis** [tskit-dev/pyslim#59]
Hello! 

as per part of this discussion:

https://groups.google.com/forum/#!topic/slim-discuss/etn7plcQRY8 
relating to outputting a vcf file with the error `Inconsistent mutations: state already equal to derived state`

Simplified scripts attached! Let me know if you need anything else

Josie 
[debug_burn_in.slim.gz](https://github.com/tskit-dev/pyslim/files/3965261/debug_burn_in.slim.gz)
[debug_mutate_to_vcf.py.gz](https://github.com/tskit-dev/pyslim/files/3965262/debug_mutate_to_vcf.py.gz)
[debug_run_balancing.slim.gz](https://github.com/tskit-dev/pyslim/files/3965263/debug_run_balancing.slim.gz)

**Comment by petrelharp** [comment]
Thanks! I'm investigating.  How long do these take to run, and how big are the tree sequence files?

Something that should not cause that error, but I think is probably not what you want:
>     initializeTreeSeq(simplificationRatio=INF, checkCoalescence=T);
This means that you'll end up with the history of *everyone alive, ever*, which makes a very large tree sequence file. Do you really need that?

**Comment by petrelharp** [comment]
Good news - setting the pop size to 100 (and the initial random seed to 23) recapitulates this bug (and takes much less time).

**Comment by petrelharp** [comment]
OK, I have a minimal working example - the problem seems to be actually a bug in `addNewDrawnMutation( )`, when applied to vectorized inputs.  Here's the SLiM script:
```
initialize() {
    // problem only happens about half the time
    setSeed(42);
	initializeTreeSeq();
	initializeMutationRate(0);
    initializeMutationType("m1", 0.5, "f", 0.1);
    defineConstant("chr_len", 10);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, chr_len-1);
    initializeRecombinationRate(0);
}

1 {
	sim.addSubpop("p1", 2);
}

1 late() {
	target = sample(sim.subpopulations.genomes, 1);
    balancing_pos = sample(0:(chr_len-1), 2);
    // THIS does not work:
	target.addNewDrawnMutation(m1, asInteger(balancing_pos));

    // THIS works:
    // for (pos in balancing_pos) {
    //     target.addNewDrawnMutation(m1, pos);
    // }

    sim.treeSeqOutput("balancing_output.trees");
    sim.simulationFinished();
}
```
and here's the python that shows the problem:
```
import pyslim

ts = pyslim.load("balancing_output.trees")

print(ts.tables.mutations)

g = ts.genotype_matrix()
```

The problem is that the second mutation is recorded *without any metadata* - no mutation type or anything SLiM-related. This is wrong, and we're lucky that tskit happened to complain about this. This does not happen if each mutation is drawn separately.

BTW @josieparis, two small corrections to your script: `balancing_pos` should be drawn out of `0:(chr_len-1)`; and I suspect that your script put down the mutations twice on accident - but, this was lucky for us because it found this bug. To get your script to work, you should be able to just use the `for` loop that put down mutations, deleting the first "add them all at once" line.

I'll move this issue over to SLiM.
