### ISSUE TITLE
SLiM ancestral state written as empty string to VCF file

### ISSUE THREAD

**Issue by kahlquist-brown** [tskit-dev/pyslim#65]
I used the workflow below to recapitate and produce a vcf. In this example there is a single sweep mutation at position 500,000, all other mutations are neutral and generated by msprime. Following these steps the vcf produced has a bug at position 500000 where there is a blank in the Ref column and a 0 in the alt column, where it should be 0 in Ref and 1 in Alt. Here is a sample, please let me know if I can provide more detail to help diagnose the bug:

1	499480	.	0	1	.	PASS	.	GT	0|0	0|0	0|0	0|0	0|0	
1	499786	.	0	1	.	PASS	.	GT	0|0	0|0	0|0	0|0	0|0	
1	500000	.		0	.	PASS	.	GT	1|1	1|1	1|1	1|1	1|1	
1	500492	.	0	1	.	PASS	.	GT	0|0	0|0	0|0	0|0	0|0	
1	500606	.	0	1	.	PASS	.	GT	0|0	0|0	0|0	0|0	0|0

>>> import pyslim, msprime
>>> import numpy as np
>>> slim_ts = pyslim.load("decap.trees")
>>> recap_ts = slim_ts.recapitate(recombination_rate=1e-8, Ne=7310)
>>> ts = pyslim.SlimTreeSequence(msprime.mutate(recap_ts, rate=1e-8,keep=True))
>>> alive = ts.individuals_alive_at(0)
>>> p1 = [i for i in alive if ts.individual(i).population == 1]
>>> p1_sample = np.random.choice(p1, size=200, replace=False)
>>> outvcf = open("test_out.vcf", "w")
>>> ts.write_vcf(outvcf, individuals=p1_sample)

**Comment by petrelharp** [comment]
Hm. Could you also post the slim code?

**Comment by kahlquist-brown** [comment]
My original script was quite large, I tried to cut it down substantially by changing the chromosome size to 10,000 bp with the slim generated mutation at 5000 bp. It will also run faster if the recombination rate and mutation rate are set lower when running the recapitation steps. This example reproduces the problem for me, let me know if you need anything else. [minimum_test_SLiM_commandline.txt](https://github.com/tskit-dev/pyslim/files/4277766/minimum_test_SLiM_commandline.txt)

**Comment by petrelharp** [comment]
Ah-ha, ok. Sorry, I should have picked up on this earlier. This is how I think *any* mutations in SLiM will be recorded in a VCF. Since SLiM has a complex model of "mutations", where a single site can have multiple different mutations at the same time on the same genome, what we record as the "derived state" of a mutation is the list of SLiM IDs of the corresponding mutations. So, the "ancestral state" at each variant site is the empty list, or "". For instance, here's from a very simple SLiM simulation, without any recapitation or anything:
```
>>> print(ts.site(0))
{'id': 0, 'position': 629.0, 'ancestral_state': '',
    'mutations': [{'id': 0, 'site': 0, 'node': 30, 'derived_state': '24', 'parent': -1,
          'metadata': [MutationMetadata(mutation_type=1, selection_coeff=0.0, population=1, slim_time=3, nucleotide=-1)]}], 'metadata': b''}
```
As you can see, the ancestral state is `''`, and the derived state is `24`. This is what shows up in the REF and ALT columns of the VCF.

So, now my question is: is this a bug? Is the empty string an invalid allele in a VCF file?

**Comment by petrelharp** [comment]
>  Is the empty string an invalid allele in a VCF file?

This seems like a "hard" question: the [documentation](http://samtools.github.io/hts-specs/VCFv4.3.pdf) requires that the REF column be only nonempty strings of ACGTN, but we already violate this by providing 0/1 genotypes:
![Screenshot from 2020-03-02 16-15-20](https://user-images.githubusercontent.com/1046249/75730249-32cce400-5ca1-11ea-9e4b-478b906c7c38.png)

Did you run into this because some VCF parsing software can't deal with it? Thanks for your help.

**Comment by kahlquist-brown** [comment]
I guess it seems odd that the genotype column contains the 0/1 encoding but the ancestral/derived columns don't match. So far I've only run into errors with my custom scripts, but I'm guessing it would break some other vcf parsing tools as well

**Comment by petrelharp** [comment]
I agree, this is easy to miss. The reason is that those mutations were generated by completely different programs (msprime for 0/1 and slim for ''/24). It does seem like we should have a way of outputting nucleotide-only VCFs, but no-one's yet proposed the how and why of that.

> I'm guessing it would break some other vcf parsing tools as well

Sounds like a good guess. But, let's see - I've just tested PyVCF and scikit-allel and bcftools, e.g.:
```
$ bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE=%GT]\n' some.vcf
1       629     .       24      tsk_0=0|0       tsk_1=0|0       tsk_2=0|0       tsk_3=0|0       tsk_4=0|0       tsk_5=1|0       tsk_6=0|0       tsk_7=0|0       tsk_8=0|0       tsk_9=0|0
1       705     .       2       tsk_0=0|0       tsk_1=0|0       tsk_2=0|0       tsk_3=0|1       tsk_4=0|0       tsk_5=0|0       tsk_6=0|0       tsk_7=0|0       tsk_8=0|0       tsk_9=0|0
1       765     .       16      tsk_0=0|0       tsk_1=0|1       tsk_2=0|0       tsk_3=0|0       tsk_4=0|0       tsk_5=0|0       tsk_6=0|0       tsk_7=0|0       tsk_8=0|0       tsk_9=0|0
1       927     .       20      tsk_0=0|0       tsk_1=0|0       tsk_2=0|1       tsk_3=0|0       tsk_4=0|0       tsk_5=0|0       tsk_6=0|0       tsk_7=0|0       tsk_8=0|0       tsk_9=0|0
1       1984    .       25      tsk_0=0|0       tsk_1=0|0       tsk_2=0|0       tsk_3=0|0       tsk_4=0|0       tsk_5=1|0       tsk_6=0|0       tsk_7=0|0       tsk_8=0|0       tsk_9=0|0
```
and everything is working fine. Any others that should be tested?

And, if this is resolved to your satisfaction, could you close this issue?  Thanks for reporting it!
