### ISSUE TITLE
finite-sites recapitation and mutation

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#77]
We've got finite-sites mutation and recombination into msprime now (https://github.com/tskit-dev/msprime/pull/946), which means we generate recombination breakpoints and mutation locations at integer sites (as an optional parameter). 

I figure that recapitation should use discrete recombination by default?

But for mutation: there's an important issue that I just realized we need to deal with first - input appreciated (@bhaller? @mufernando?).  We've coded things up to be quite general - you give it a `root_distribution` and a `transition_matrix`; the allele at the root of the tree gets chosen from `root_distribution`, and subsequent mutations look at the previous state, and pick a new state from the appropriate row of the `transition_matrix`. And, the `msprime.mutate( )` function will optionally `keep` any existing mutations in the tree sequence, as we want for SLiM. However, since the probability of mutation to a `B` might depend on the previous state, I have made it an error to try to simulate new mutations that are ancestral to any existing mutations, if they are to be kept. 

As an example of why this should be an error, suppose in the existing tree sequence at some site the ancestral state is A and the derived state is T, and we want to add a new mutation somewhere *between* the two.  Well, what we should do is to pick C with probabiilty proportional to the probability of mutation A->C->T... but this is quite tricky, especially since there could be several different derived mutations.

This means that if we have a tree sequence that already has mutations at discrete sites over the last 100 years but not before, we can't add new mutations at discrete sites on the earlier time period.  Which is of course what we really want to do for SLiM.

What to do about this?

1. The most coherent option might be to put the mutations on *backwards* up the tree - so, instead of starting at the root and moving down the tree, figure out what the conditional distribution of the ancestral mutation is given its derived state. This is possible but pretty complicated - you have to do phylogenetic calculations over the whole tree instead of looking at each mutation separately, and you have to assume the mutation model is stationary (which is ok).

2. Another option would be to disable the check under "parent-independent mutation" - i.e., the chance of mutating `A -> B` doesn't actually depend on what `A` is. So, we could basically only recapitate using very simple mutation models (eg Jukes-Cantor). This wouldn't be too bad.

3. Or, we could implement "finite sites but don't hit any already-mutated sites". So, when we add mutations to an already-mutated tree sequence, we ask msprime to put the mutations down at integer sites (and hence some sites could be hit more than once), but to please avoid any sites that already have mutations on them. (We'd have to figure out the precise details.) This is odd but maybe the right way to go, because for the standard use case of adding neutral mutations to a SLiM simulation, it actually seems maybe wrong to be able to have more than one mutation at a given site for which some are neutral and some are non-neutral. (at least without mutation stacking, etcetera).

4. Or, I guess we could disable this check entirely (optionally), and let the user worry about the possible nonsensical mutations that might occur.

I guess I'm voting for either (3) or (4). The seeming inconsistency in (4) is maybe OK, because if you're applying mutations to different bits of the tree sequence in different chunks, then why should those models be consistent? If really you want all mutations to be consistent with a single model, you should mutate in the forwards-time ordering.

Really, this will be an msprime issue, but I'm putting discussion of it here because it overlaps with asking what good behavior for SLiM should be.

**Comment by bhaller** [comment]
Very interesting.  It's awesome that you guys have this working; people have been itching for this feature, it seems like!

First of all, it is maybe even more complex than you laid out here:

> As an example of why this should be an error, suppose in the existing tree sequence at some site the ancestral state is A and the derived state is T, and we want to add a new mutation somewhere between the two. Well, what we should do is to pick C with probabiilty proportional to the probability of mutation A->C->T... but this is quite tricky, especially since there could be several different derived mutations.

Because it might be that the new mutation you want to introduce between the A and the T would be an T!  That would be perfectly fine and logical if it turns out that you're going to put *another* mutation below, before you get to the derived T, right?  Then you'd have, for example, A->T->C->T as the history at that site.  So unless you have pre-planned all of the mutations that you're going to add all the way down, you don't know what the set of mutations you can draw from is.  Or perhaps I'm missing something?

But assuming that's a non-issue for some reason, I think my vote, in order of preference, would be:

- Offer the user the choice between (2), (3), and (4).  It sounds like those would all follow a very similar implementation path, so maybe this is just a switchable option?  That seems best, since people's requirements vary so widely.

- (4).  Let people field it themselves.  It shouldn't be too difficult for them to get from (4) to (3) themselves, by just scanning for collisions and eliminating them from the recapitated history, right?

- (2).  Somewhat limiting, but completely self-consistent and without gotchas.  Safe, reliable, easy to document, easy to understand.  And potentially extensible to allow any of the other choices down the road, if desired, so it keeps our options open.

- (3).  I'm not crazy about this, because it sounds like it would actually distort the mutational structure in a weird way; you'd have a deficit of mutations in the recapitated block overall, and sites would either mutate during the recapitated block or during the simulated block but not both.  It's not obvious how that would bite someone's analysis, but it's not obvious that it wouldn't, either.  And if you have a high mutation rate and a long forward-simulated time, it might be that most/all sites would have received a mutation at some point during forward simulation, right?  So then you'd be unable to overlay mutations in the recapitated block at most/all sites, and that would be really weird, and probably *would* distort analyses.

The other thing I'd observe is that even in nucleotide-based models SLiM can simulate non-nucleotide mutations that can represent things other than base changes – inversions, microsatellite changes, epigenetics, who knows what.  Such non-nucleotide mutations should certainly not alter how msprime decides to overlay mutations; they should be treated by your code as being invisible, in effect.  Indeed, you might run a non-nucleotide-based model in SLiM because the *only* mutations you need to forward-simulate are non-nucleotide-based, but then want to have msprime overlay the whole nucleotide-based mutational history on top of that.  So that should be possible.  And similarly, I suppose all this will work for non-nucleotide-based mutations in msprime too, right?  You're talking here in terms of nucleotide changes and their consistency, but people will be able to do integer-position recapitation/overlay for non-nuc models too, right?

Other thoughts:

- Is there anything that will need to change in SLiM in conjunction with this?  I'm preparing to release SLiM 3.4 fairly soon now, but I can hold it for necessary changes, rather than have to roll a 3.4.1 release in response to this shift.  But offhand I don't see what would change on the SLiM side, unless there's a change that would need to be made to allow SLiM to read back in the generated mutations properly.  (But presumably you can fix all annotation issues in pyslim, so that it looks identical to a SLiM-generated file, once the positions are integers.)

- Whatever choice you make, document it very explicitly; this seems like an area where people will be confused and need help.

I hope these random comments are somehow clarifying.  :->  Great stuff!

**Comment by mufernando** [comment]
I agree with Ben that giving the option of 2, 3 or 4 would be best.

I quite like option 2 because the model choice would be explicit to the user. If someone wants sims with a different mutation model they'd have to do it forward-in-time.

At first I didn't think 3 would be too bad, but I had in mind shorter SLiM sims with animal-like mutation rates. This would be similar to doing SLiM sims without stacking, I think.

Option 4 is great because if someone wants to implement a different solution they could.

**Comment by petrelharp** [comment]
Thanks for helping me think this through!  I've thought more, and realized I wasn't thinking totally clearly about how exactly we'd do this with SLiM's mutations.

So: the mutation code we've just got into msprime works in the usual phylogenetics way, with a finite alphabet and a matrix of transition probabilities, etcetera. SLiM alleles on the other hand, are comma-separated lists of mutation IDs. We could put new mutations above existing SLiM mutations and just ignore that some came after, no problem, but if we tried to put any *below* existing mutations we'd have a problem for two reasons: 
- the ancestral state wouldn't make sense so we couldn't pick a new state (unless it was parent-independent mutation), but worse,
- suppose the existing mutation was non-neutral; if we stuck a new mutation below it we'd be removing that non-neutral mutation from the samples below it, thus changing their *phenotype*, which would be bad.

Happily, there's a pretty easy solution. The "pick an allele at the root" and "pick a new allele given the previous allele" functions are properties of the mutation model in the new code; so, we just need to write new functions for these two things, in C, and pass in our own mutation model through pyslim. These are [pretty simple](https://github.com/tskit-dev/msprime/blob/39cd6c973b038fd173b763c2cd363557db00a314/lib/mutgen.c#L758), and it would take some minor refactoring to but no big deal.

Note that the current mutation code already makes it possible for people to simulate with msprime, annotate the mutations so that some are selected, then start a SLiM simulation with them.

So: here's my current proposal for how to add neutral mutations on top of existing SLiM-produced mutations. The mutation generation code will take care of *where* to put them, so we just need to specify what happens. In brief, we'll treat the new mutations just like a new mutation type, and "stack" them. We'll need to first figure out where to start with assigning mutation IDs; let's say we did this and give the new mutation in question the id `mid`:

1. At previously unmutated sites, the ancestral state is `""` and the derived state is `mid`.
2. New mutations whose parental allele is `x` have derived state `x,mid`.

Also, the metadata would be set to contain SLiM-metadata for the mutations in question.

If we're really stacking mutations, though, we should really also do:

3. Existing mutations with derived allele `x` that have a new mutation inserted above them are modified to have allele `x,mid`.

This bit is more annoying, though, and we should probably do it in post-processing by pyslim.

How does this sound? I'm thinking about what we want to do with these data downstream:
- compute statistics with the genomes, like finding out how many mutations differ between sample A and sample B.
- look up the genotypes *as seen by SLiM* of the samples

I think this proposal gives us sensible answers to both of these questions, Addition (3) above also gives us sensible genotypes in terms of neutral mutations.

The main thing I'm not sure about is: what if someone is running a simulation with stackPolicy="last"? I argue it's still OK to stack mutations here, since they're neutral and so don't do anything. It's a bit confusing but if we don't stack them then I think our only consistent option is to go back to option (3) above, just leave already-mutated sites alone.

What do you think?  Once we get a plan I can figure out what needs to happen on the msprime side...

**Comment by bhaller** [comment]
Sorry for the slow reply, this got a bit buried.

> So: here's my current proposal for how to add neutral mutations on top of existing SLiM-produced mutations. The mutation generation code will take care of where to put them, so we just need to specify what happens. In brief, we'll treat the new mutations just like a new mutation type, and "stack" them.

Yeah, this seems right.  Just overlay, passively retaining the mutations already present, not trying to lead up to them or lead away from them.

> Existing mutations with derived allele x that have a new mutation inserted above them are modified to have allele x,mid.

This is indeed annoying.  I don't see a solution besides patching all the allelic states below the new mutation.  The data structure just isn't really designed for efficient introduction of new stacked mutations above existing mutations.

> The main thing I'm not sure about is: what if someone is running a simulation with stackPolicy="last"? I argue it's still OK to stack mutations here, since they're neutral and so don't do anything.

Well, for non-nucleotide-based mutations that is probably fine.  Stacking will presumably be rare anyway, so it shouldn't throw people's analysis off significantly.  But I think there may be more issues with nucleotide-based mutations.  You certainly want to avoid the situation where you have two stacked mutations in a genome, one of which says the nucleotide at the position is "A" and the other of which says it's "T".

> It's a bit confusing but if we don't stack them then I think our only consistent option is to go back to option (3) above, just leave already-mutated sites alone.

For nucleotide-based models, that may be necessary for consistency.  So I do think supporting more than one of these choices – (2), (3), or (4), in the original formulation – might be both necessary and desirable.  I'm not sure I'd get into the game of trying to *force* people to do the right thing, in such a way that the resulting pattern of mutations really makes sense and is self-consistent; let people do what they want.  But providing the flexibility so that they can achieve a good, desirable, consistent result should be the aim.

**Comment by petrelharp** [comment]
Thanks. I need to get back on this soon-ish while it's still in my head.

Question: if we go ahead with the above plan, and do the metadata right, will we be able to read the resulting tree sequences back into SLiM? (Or, what do we have to do to make sure that works, especially for nucleotide models?)

**Comment by bhaller** [comment]
If a tree sequence is self-consistent, uses integer positions for everything, and has complete, compliant metadata, it should be readable; I don't see why not.  SLiM can certainly read in tree sequence files for nucleotide-based models, etc.  I guess the question is: in what way would the resulting tree sequences differ from a tree sequence that SLiM could have produced itself?  If there is no difference, then they should certainly be loadable.  If you see a potential difference, then that would be a potential problem... do you?  (Sorry if this should be obvious – I think my brain is not as much in this game yet as yours is.  If you want to skype about it or something, I'm happy to.)

**Comment by petrelharp** [comment]
Well, any gotchas that occur to you - the main thing I was wondering about was the inconsistent nucleotide thing: what's the consistency rules there? I don't have the nucleotide model rules in my head very well.

**Comment by petrelharp** [comment]
Hm, I found this in the manual:
> In a nucleotide-based model,
mutationType might still be non-nucleotide-based (in which case nucleotide must still be
NULL ), or mutationType might be nucleotide-based, in which case a non- NULL value must be
supplied for nucleotide , specifying the nucleotide(s) to be associated with the new
mutation(s). Nucleotides may be specified with string values ( "A" , "C" , "G" , or "T" ), or with
integer values (A= 0 , C= 1 , G= 2 , T= 3 ). If a nucleotide mutation already exists at the mutating
position, it is replaced automatically in accordance with the stacking policy for nucleotide-
based mutation types. No check is performed that a new mutation’s nucleotide differs from
the ancestral sequence, or that its selection coefficient is consistent with other mutations that
may already exist at the given position with the same nucleotide; model consistency is the
responsibility of the model.

... so it sounds like anything goes? (Note: I'm not clear from these docs about what if the stack policy is "s"? What's the nucleotide coming out at the end?)

**Comment by bhaller** [comment]
I'm pretty sure SLiM doesn't do any checking of nucleotide consistency, either at load time or in SLiMSim::CrosscheckTreeSeqIntegrity(), except ensuring that mutations with nucleotide-based mutation types do specify a nucleotide, and mutations of non-nucleotide-based mutation types do not.  So I think it would probably be possible, and have no consequences for SLiM, to construct a mutational history that SLiM would not have produced and load it into SLiM.  As long as that mutational history is *representable* by both SLiM's data structures and the tree-sequence tables, and the two match such that they pass crosscheck, you should be fine.  If a mutational history is not even representable by SLiM, somehow, then of course you've got a problem; but offhand I can't really imagine what that would mean in practice.

Note that SLiM generates its data structures on load by using a vargen_t to loop over the trees, get variants at each site, and create the appropriate mutations in the appropriate individuals.  If something about the inconsistency of the tree sequence confuses vargen_t, then things will probably go south.  But again, I don't know what would cause that in practice.  This might be an area where we just choose the design that seems right and clean up problems afterwards; if SLiM's consistency checks are somehow unnecessarily strict we can (perhaps optionally) relax them, or if they are not strict enough and they allow something in that causes problems, we can strengthen them.  This stuff is complex enough that it's hard to anticipate every contingency.

> (Note: I'm not clear from these docs about what if the stack policy is "s"? What's the nucleotide coming out at the end?)

In SLiM, nucleotide-based mutation types are all forced together into a single stacking group with policy "l"; that cannot be changed.  Nucleotide-based mutations can stack with non-nucleotide-based mutations, but not with each other.  That would be a good constraint to make sure you enforce on your end, otherwise things like generating nucleotide sequences for genomes, generating VCF output, etc., would all break.  Possibly it would be OK for them to stack as long as their nucleotides are identical, but I'm not sure; unless you really need to allow that for some reason, it seems pretty nonsensical and I'd recommend disallowing it.

**Comment by bhaller** [comment]
Regarding that last point, one relevant spot in the manual is this:

> Nucleotide-based mutations always use a `mutationStackGroup` of -1 and a `mutationStackPolicy` of `"l"`. This ensures that a new nucleotide mutation always replaces any previously existing nucleotide mutation at a given position, regardless of the mutation types of the nucleotide mutations. These values are set automatically by `initializeMutationTypeNuc()`, and may not be changed.

**Comment by bhaller** [comment]
I think I'd add a third concern: (c) while we don't need to become the consistency police, users should be *able* to produce self-consistent results if they want to, reasonably easily, and if they produce inconsistent results, they should *know* that – the choice between "consistent" and "inconsistent" should be clearly visible in the usage pattern of the APIs, not a subtle thing that bites people accidentally and confuses them.

**Comment by petrelharp** [comment]
This discussion led to making the `SLiMMutationModel( )` in msprime, so I"ll close this (but also see #225).
