### ISSUE TITLE
provide an example of how to "post-capitate"

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#88]
Use case: suppose you use SLiM to simulate a short period of selection (eg a single sweep), that happened a long time ago. You can recapitate to get the history before, but then what 
about the long time *after* the sweep? To do this, we could

1. save the tree sequence in SLiM at the end of the sweep
2. separately, use msprime to simulate for the desired amount of post-sweep time
3. attach the resulting two tree sequences to each other with `union()`

It'd be nice to write this up as a vignette (maybe here, maybe in tskit's docs?).

*Note:* `union` will be available in the next tskit release (soon).

**Comment by bhaller** [comment]
Super cool that this will be possible with the new tskit!

The only other thing we need is a good name!  :->  I know I said "post-capitate" before, but I think that's not a good name.  Kind of confusing, since "recapitate" implies that the "head" of the tree sequence is back in ancestral time.  So what we're talking about doing here is adding "feet", in that analogy, but I'm not sure "repeditate" or anything along those lines would be a good name either.  Although it might make people laugh, at least.  :->  Words like "extension" or "continuation" seem a little too generic, they're not interesting enough to sound like they represent a process analogous to recapitation.  "Finalization"?  "Resolution"?  I kinda like "finalization".  Thoughts?

And I'm not suggesting that we need to push a new jargon term as hard as we've pushed the term "recapitation".  For one thing, this operation will probably be much less common than recapitation.  But we do need a term to refer to what's being done; we need a title for the vignette, etc.  "Finalization" seems pretty good to me...?

**Comment by petrelharp** [comment]
Oh, this was done: https://pyslim.readthedocs.io/en/latest/vignette_continuing.html
